version: '3'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_DATABASE
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ~/db/${DB_DATABASE}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - postgres
  files-db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_FILES_PASSWORD
      POSTGRES_USER: $DB_FILES_USERNAME
      POSTGRES_DB: $DB_FILES_DATABASE
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ~/db/${DB_FILES_DATABASE}:/var/lib/postgresql/data
    ports:
      - ${DB_FILES_PORT}:5432
    networks:
      - postgres
  files-read:
    image: nginx:latest
    volumes:
     - ${FILES_ROOT}:/www/data
     - ./nginx/file-server.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "8080:80"

networks:
  postgres:
    driver: bridge


