import Head from "next/head";
import Link from "next/link";

export function MainPage(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Main Page</h1>
      </header>
      <main>
        <Link href="/dashboard" passHref>
          Test Next.js routing!
        </Link>
      </main>
    </div>
  );
}
